# This is a basic workflow that is manually triggered

name: Angular Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install dep
        run: npm install node-sass
      - name: build
        run: npm run build
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
